### ISSUE TITLE
limitar a 1 metro de lado

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#12]
Não permitir célula ou subgrade inferior... Talvez na própria API PostgreSQL limitar. Na inferior a 1m.

![image](https://user-images.githubusercontent.com/1651447/199361719-1b84fbb6-a999-4887-9b53-fff25adf9a0e.png)

**Comment by 0e1** [comment]
ver tb: https://github.com/osm-codes/gridMap-draftPages/issues/10
