### ISSUE TITLE
Tooltip de subgrade não mostra dados corretos

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#15]
Ao clicar em subgrade (ou ponto dela como ilustrado) as informações não são consistentes com o município. No caso de "ponto" ainda é "descritor de célula indicada pelo seu ponto central", então requer área. 

![image](https://user-images.githubusercontent.com/1651447/199559529-60b5f007-5861-4b6d-b55e-6c277b1420e5.png)

**Comment by ppKrauss** [comment]
Ver também #18

**Comment by 0e1** [comment]
Resolvido.
