### ISSUE TITLE
Tooltip fora de posição ou sumido

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#18]
Mesmo apertando denovo o botão de mostrar tooltip

![image](https://user-images.githubusercontent.com/1651447/200179086-90afd089-5ef0-4d66-a57d-664ad533f9cb.png)

Qualquer pais, ex. https://osm.codes/BR-SP-SaoPaulo~3CUYBG
![image](https://user-images.githubusercontent.com/1651447/200179178-92feeeac-17c6-43df-ab71-1af46b411883.png)

**Comment by 0e1** [comment]
Consolidada em https://github.com/osm-codes/gridMap-draftPages/issues/56#issuecomment-1548419263.
