### ISSUE TITLE
Requisitos pendentes para postal

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#2]
## Mapa
- [x] Não permitir navegação para fora da bbox da cidade

### Passo1 

- [x] No na side-box usar a seguinte sequência de botões meios para interatividade: 

![image](https://user-images.githubusercontent.com/1651447/198574648-38510979-a781-476f-a324-6f3c33e03133.png)

- [x] reordenar conforme ilustrado
- [x] manter cidade como seletor e prefixo ISO (ex. `BR-PB`) como link. Quando clica fora do mapa, muda de seletor para link da cidade externa, sugerindo que se pode navegar para ela para obter mais do que área de fronteira.
- [x] seletor grid deixa de ser "grid" e passa a ser apenas um seletor com 3 opções, {"sem grade", "com grade", "grade de pontos"}.
- [x] na box do botão "Encode" vale tudo, por exemplo `urn:lex:sp;sp;campinas` ou `geo:olc:589JHCXV+WG`. Em particular o click de mouse fornece GeoURI.
- [x] demais controles mais em baixo isolados.
 
### Passo 2

Estudar concorrentes e imaginar como destacar a caixa do geocódigo (ver layout do Eircode, CSS de caixa inferior do PlusCodes, Mapcode etc) 

Retornar as informações do ponto ou geocodigo na side-box, não no mapa (exceto se solicitar popup num segundo click sobre o ponto).

**Comment by ppKrauss** [comment]
Complementando os requisitos do passo1:
* máximo 2 ou 7 casas decimais na LatLong do click de mouse no mapa.
* o mapa precisa ficar "preso" no município, nao deixar sair da área do fit dele.
* no on-mouse-over do ponto clicado  (célula) não mostrar tooltip se estiver em checkbox sem tooltip
* quando entra com URL de ponto, por exemplo https://osm.codes/CO-RIS-Pereira~4F5  , carregaer e mostrar o  municipio na hora do zoom-out.

**Comment by ppKrauss** [comment]
priorizar

**Comment by ppKrauss** [comment]
Mudança de requisito 

## no layout do seletor de jurisdição

Ao **invés de**
![image](https://user-images.githubusercontent.com/1651447/200175216-2797cdef-f151-415e-951d-a20c2e9d766a.png)

Apresentar um por linha, jurisdição e geocódigo da grade postal:

![image](https://user-images.githubusercontent.com/1651447/200175747-8842eebb-82f7-47c4-982d-fdf868764ad3.png)

## no layout do Encode
Ao invés do simples 
![image](https://user-images.githubusercontent.com/1651447/200176644-f4348346-e368-4fec-ab96-09e5a00064ca.png)
Acrescentar antes a frase `Equivalent Geo URI:<br/>`

## no final
Ao invés de apenas geocódigo científico,
![image](https://user-images.githubusercontent.com/1651447/200177055-a62a7025-cf34-4265-8fe0-941159b39e31.png)
Usar:
```
Equivalent cell: 
<br/>&nbsp; in official geocode: $nominal~$grade
<br/>&nbsp; in the Scientic grid: $scientific
<br/>&nbsp; for QRcode: $codigo_paisBase32_absoluto
```

**Comment by 0e1** [comment]
Testar o suporte a `(urn|geo):lex:.+` no botão de encode na interface logística em http://test.osm.codes. Verificar se é retornado a jurisdição e a cobertura da jurisdição (se ela existir).

**Comment by ppKrauss** [comment]
> botão de encode
Esse?  **bug**: não faz nada. No contexto https://test.osm.codes/BR-BA-AguaFria  o `urn:lex:br;sp;sao.paulo` deveria ser equivalente a trocar a jurisdição.

![image](https://user-images.githubusercontent.com/1651447/232324356-24c0d9f8-5673-41eb-b28b-419c0bbe8ace.png)

**Comment by 0e1** [comment]
Faltava um `\.` nas regex. Corrigido. Agora funciona.

**Comment by 0e1** [comment]
Considero todos os itens atendidos. 

> <br/>&nbsp; for QRcode: $codigo_paisBase32_absoluto

Linha está comenta em https://github.com/osm-codes/gridMap-draftPages/blob/main/logistic/index.html#L32 enquanto não for implementada https://github.com/osm-codes/gridMap-draftPages/issues/14.
