### ISSUE TITLE
Decisões e correções na URL com geo

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#20]
Atualmente se uso https://osm.codes/geo:-22.870490,-47.038992;u=100
caio numa situação ambígua, quase um ornitorrinco:

![image](https://user-images.githubusercontent.com/1651447/200433122-c8154ba2-87be-4e63-b996-9f2087323f64.png)

* URL da Colômbia
* Célula com OSMcode Postal
* Página de OSMcode Científico
* ...
Antes de corrigir, precisamos tomar decisões.

**Comment by 0e1** [comment]
Os commits referenciados acima ajustam o suficiente para redirecionar para a grade postal.
