### ISSUE TITLE
Jurisdiction code redireciona mas não carrega nome do titulo

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#21]
Nome da cidade ficando em branco, apesar do link funcionar. Por exemplo https://osm.codes/CO-15001-8GZZN

![image](https://user-images.githubusercontent.com/1651447/201725520-a64903f2-a2df-44c5-98d4-edc6b9772d7a.png)

até redureciona para   `CO-BOY-Tunja~8GZZN`, mas não parece o nome Tunja.

**Comment by 0e1** [comment]
Foi resolvida.
