### ISSUE TITLE
Incerteza da Geo URI não pode ser zero

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#23]
Arredondar para cima (Javascript `Math.ceil`). 
![image](https://user-images.githubusercontent.com/1651447/202160518-8cf86905-bffe-4d0c-8ae4-b7827d6cca0b.png)

**Comment by 0e1** [comment]
Com incerteza sendo um número natural não-nulo não conseguimos acessar células próximas numa grade cientifica (1, 1.4 e 2.8). Decidimos usar um valor real não-nulo, arredondando valores maiores que 5m. 

Pendente esclarecer, na Wikipédia inclusive, se incerteza se refere a raio ou diâmetro.

**Comment by ppKrauss** [comment]
**Decisões de projeto**:
1. O redirecionamento  *default* do endpoint `https://osm.codes/geo:{x},{y}{etc}` é o OSMcodes postal.<br/>Justificativa: por ser o mais procurado.
2. A incerteza `u` será interpretada como **diâmetro** do disco de incerteza em torno da localização.<br/> Justificativa: a incerteza quando informal (como na [RFC&nbsp;5870](https://www.rfc-editor.org/rfc/rfc5870)) refere-se à largura total ou intervalo, sem suposição de simetria. A incerteza implícita na  notação `X±R` requer simetria e a noção de raio...Por isso pendente  confirmar http://gis.stackexchange.com
3. `u=0` será arredondado para o menor valor permitido na grade postal do país que contém o ponto.
4. `0<u<=9` será arredondado com uma casa decimal antes do "snip to grid".
5. demais valores, `u>9` será arredondado para inteiro antes do "snip to grid".
