### ISSUE TITLE
Modo grade mostra geocódigo-titulo estranho e incompativel com URL 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#24]
Experimente usar click com grade, depois de https://osm.codes/BR-SP-SaoPaulo~32

![image](https://user-images.githubusercontent.com/1651447/202299759-dbd2329e-e51f-493d-96e1-7b91f1b8f1dc.png)

PS: sem grade funciona:
![image](https://user-images.githubusercontent.com/1651447/202299540-9af27338-a565-44ec-ac70-7bc9681c6b0b.png)

**Comment by 0e1** [comment]
Foi resolvida.
