### ISSUE TITLE
Resolver melhor defaults e/ou mecanismo zoon-click

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#25]
O zoom da URL, por exemplo https://osm.codes/BR-SP-SaoPaulo~QD1VR  está bom! <br/>O problema é quando fazemos o click num ponto do lado, aí fica com zoom demais. 

## Solução do zoom-click

**Alternativa 1:**

Repetir o comportamento da [URL ponto](https://osm.codes/BR-SP-SaoPaulo~QD1VR) nos eventos de zoom-click. Talvez já resolva.

**Alternativa 2:**

* no caso de [entrada na página por URL de ponto](https://osm.codes/BR-SP-SaoPaulo~QD1VR), desabilitar zoom-click por *default*.
* no caso de [entrada pela cidade](https://osm.codes/BR-SP-SaoPaulo), **o primeiro click** é um evento especial, precisa gerar comportamento da URL-ponto, fazendo o zoom-click adequado e depois desabilitando. Mas só o primeiro click depois da "entrada vazia".

## Solução do click-célula

No caso de células grandes (ex. [BR-SP-SaoPaulo~39M](https://osm.codes/BR-SP-SaoPaulo~39M)), pode manter como está, mas no caso de click-célula pequena, caso de [BR-SP-SaoPaulo~39X9G1](https://osm.codes/BR-SP-SaoPaulo~39X9G1), não pode dar zoom demais, manter solução anterior.

![image](https://user-images.githubusercontent.com/1651447/203681499-5fc805f6-e836-45aa-87e3-f833d3d096c6.png)

**Comment by 0e1** [comment]
Utilizada a alternativa 1.
