### ISSUE TITLE
Permitindo digitos além do máximo no geocódigo

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#28]
O número de níveis é sempre limitado, se o usuário tenta por Javascript deve dar alerta de erro, se tenta por URL, descartar os dígitos a mais (se possível alertar do descarte). 

`alert("Número de dígitos no geocódigo excedeu o limite de níveis da grade")`.

Bug no geocódigo postal, ver análogo no científico:
![image](https://user-images.githubusercontent.com/1651447/210217559-849a78a9-2c8b-4931-af8d-a11b171a1c6a.png)

**Comment by 0e1** [comment]
As células de coberturas podem ter tamanhos diferentes em cidades diferentes.

Para fazer o controle do lado do cliente, precisaríamos saber qual o tamanho da célula de cobertura para um dado ggeohash.

Penso que o caminho é resolver no servidor, retornar um código de erro, quando for necessário truncar o ggeohash, e tratar esse código no cliente.
