### ISSUE TITLE
Opção de desenhar o municipio

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#3]
Por exemplo https://osm.codes/CO-RIS-Dosquebradas~KX
abre a página sem o poligono da jurisdição: cirar um botão para ver a jurisdição ... Ou carregar e mostrar a partir de um certo zoom-out.

**Comment by 0e1** [comment]
Ver exemplo de carregamento da jurisdição: Ver exemplo: https://osm.codes/BR-AM-Barcelos~9L0S7K8, https://osm.codes/BR+10CFA1058T
