### ISSUE TITLE
Cobertura ausente

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#32]
Ver https://osm.codes/BR-SP-CamposNovosPaulista

**Comment by 0e1** [comment]
Coberturas que faltavam:

https://test.osm.codes/BR-AM-Anori
https://test.osm.codes/BR-BA-MadreDeus
https://test.osm.codes/BR-MA-Brejo
https://test.osm.codes/BR-SP-Alvinlandia
https://test.osm.codes/BR-SP-Anhumas
https://test.osm.codes/BR-SP-Assis
https://test.osm.codes/BR-SP-CabraliaPaulista
https://test.osm.codes/BR-SP-CamposNovosPaulista
https://test.osm.codes/BR-SP-Charqueada
https://test.osm.codes/BR-SP-Duartina
https://test.osm.codes/BR-SP-EngenheiroCoelho
https://test.osm.codes/BR-SP-EstrelaNorte
https://test.osm.codes/BR-SP-Iepe
https://test.osm.codes/BR-SP-Limeira
https://test.osm.codes/BR-SP-Lucianopolis
https://test.osm.codes/BR-SP-Lupercio
https://test.osm.codes/BR-SP-Nantes
https://test.osm.codes/BR-SP-Ocaucu
https://test.osm.codes/BR-SP-Piratininga
https://test.osm.codes/BR-SP-Ubirajara

**Comment by 0e1** [comment]
Coberturas brasileiras completas. Testar as coberturas que faltavam e foram adicionadas. Ver comentário anterior.

**Comment by IgorEliezer** [comment]
> 1. ao clicar no link os seletores devem ser populados;

O que seria "seletores devem ser populados"? Quando eu clico num link (e.g. https://test.osm.codes/BR-AM-Anori), abre um mapa com o contorno do município e só ([ver captura](https://user-images.githubusercontent.com/4673289/234892593-1be94a8e-d926-4230-9ec2-560cb0580961.png)). Teria que aparecer algo mais?


> 2. verificar se não existe falha na cobertura (ao clicar no botão coverage);

Todos funcionam.


> 3. Se encode/decode funcionam.

Todos funcionam.

**Comment by IgorEliezer** [comment]
@0e1 Respondido.

**Comment by 0e1** [comment]
> Só um detalhe: se você escolher `- opt -` em estado ou `- City -` em município, a página irá retornar "404 Not Found".

Impedi esse comportamento nos commits referenciados acima. Deve redirecionar apenas quando estado e município forem selecionados.
