### ISSUE TITLE
Passar geo URI para dentro do mapa

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#37]
A atual gasta uma linha inteira, não pode. 

![image](https://user-images.githubusercontent.com/1651447/223091022-b61cce36-8c55-49bc-bc9d-64cca899b639.png)

Ideal  dentro do mapa. Uma solução seria passar para o canto superior direito,  

![image](https://user-images.githubusercontent.com/1651447/223090623-ca9c5bbd-aeb4-422e-8af4-1ca9a435528d.png)

Avaliar: outra solução, tendo em vista a [issue 27](https://github.com/osm-codes/gridMap-draftPages/issues/27), seria jogar no rodapé antes (e afastado) da escala.
 
------

Além disso, outro requisito, é que quando o nível maior que L14, precisa acrescentar mais um dígito.

**Comment by 0e1** [comment]
Pode testar.
