### ISSUE TITLE
Seletor de níveis com erro

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#39]
Não pode apresentar níveis superiores à jurisdição: o melhor é que todos esses **parâmetros sejam fornecidos pela API no ato da carga da jurisdição**, garantindo que o Javascript nunca erre.

![image](https://user-images.githubusercontent.com/1651447/229284619-84ea97e4-557b-4d3c-bdb2-405c2d3ff236.png)

**Comment by 0e1** [comment]
Pode testar.

**Comment by 0e1** [comment]
@IgorEliezer por favor testar.

Escolha umas 3 cidades de forma aleatória. O menor _level_ exibido no select deve ser compatível com o maior _side_ das células de cobertura (exibida usando o botão _coverage_).

Por exemplo, em https://test.osm.codes/BR-SP-Ocaucu _L5 (33km)_ é compatível com _Side:32.77km_.

**Comment by IgorEliezer** [comment]
@0e1 Testado. OK.
