### ISSUE TITLE
Nivel intermediário não está persistindo no seletor de níveis

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#4]
Por exemplo 

1. Entro em https://osm.codes/CO-RIS-Pereira
2. Seleciono **L7.5** (de 1.45 km)
3. clico no mapa: ok ... Mas ao clicar já magicamente muda o *level*
4. clico de novo e a célula está em **L5** (!), um nivel acima

![image](https://user-images.githubusercontent.com/1651447/198845353-d480a0e1-591e-4def-8107-d390a752ed8f.png)

**Comment by 0e1** [comment]
Corrigido.
