### ISSUE TITLE
Transferir definições server-side para WS

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#42]
As definições de "gridMap pages" **se restringem à interface *client***. Todos os web-services e definições server-side devem ser mantidas e documentadas em WS ou as libs por ele convocadas (ex. GGeohash).

Documentar o fato e mudar [`conf.nginx`](https://github.com/osm-codes/gridMap-draftPages/blob/main/conf.nginx) para https://github.com/osm-codes/WS/blob/main/src/conf.nginx

**Comment by 0e1** [comment]
Configurações movidas para https://github.com/osm-codes/WS/tree/main/src/nginx.
