### ISSUE TITLE
Persistir as subgrades

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#44]
Na interface de grade cientifica voltar ao que era antes: persistir as grades, ou seja, vários clicks, não só o corrente.

![image](https://user-images.githubusercontent.com/1651447/231138065-84ac33b0-ca77-4fcf-9d29-94c27d3d0014.png)

**Comment by IgorEliezer** [comment]
> Por default deve ser exibido no mapa os grids de todos os clicks no mapa.

Não é o que está acontecendo. Quando eu clico em um novo local, o mapa remove a última quadrícula selecionada. Clico de novo, remove a última seleção.

Na interface normal, as quadrícula selecionadas vão se mantendo ao passo que vou clicando.

**Comment by 0e1** [comment]
Você acabou testando após eu simplificar a interface cientifica (https://test.osm.codes/BR+dfb5ba2a8t). A funcionalidade de persistir grids ficou apenas na interface cientifica completa em https://test.osm.codes/scientific_full/BR+dfb5ba2a8t.
