### ISSUE TITLE
Level e click geocódigo incompatíveis

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#47]
![image](https://user-images.githubusercontent.com/1651447/232324648-ab43c163-4784-4754-8979-cbe3d9459636.png)

**Comment by 0e1** [comment]
Não enxerguei a incompatibilidade.

No caso, _L17.5(6m)_ é o level para a célula [6NWZP](https://test.osm.codes/BR-PE-Barreiros~6NWZP) de lado _5.66 m_.

**Comment by 0e1** [comment]
@IgorEliezer por favor, testar em algumas cidades ou países se o informado em **Level** é compatível com o informado em **side**. Testar em https://test.osm.codes.
