### ISSUE TITLE
Disponibilizar imagem de satélite como camada de fundo

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#49]
O site não tem disponível uma camada de fundo de imagem de satélite. 

![image](https://user-images.githubusercontent.com/4673289/236650667-df4d28ec-e58f-4f92-b3e6-43ef8035ce33.png)

@0e1 favor ver.

(similar a #38)

**Comment by 0e1** [comment]
Issue https://github.com/osm-codes/gridMap-draftPages/issues/38 trata desse assunto, por isso fecharem essa.
