### ISSUE TITLE
postal, usar nome da cidade no titulo

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#5]
O título fixo do HTML, `<aside id="custom-map-controls"><h1>Postal OSMcodes</h1>..`, passaria a ser dinâmico. Por exemplo `<h1>Postal OSMcodes of <i></i></h1>` pode ser referenciado por um `id` ou por <br/>`document.querySelector("#custom-map-controls  i").innerHTML = "Nome da Cidade"`

![image](https://user-images.githubusercontent.com/1651447/198852851-a4921c55-fac6-4cdb-95ce-a21a6dabbcc0.png)

Como o nome da cidade é agora obrigatório (podendo aparecer alguns segundos depois se for página com URL de célula), sempre teremos um nome **após a carga do GeoJSON da cidade**.

**Comment by 0e1** [comment]
Ver exemplo: https://osm.codes/BR-AM-Barcelos~9L0S7K8
