### ISSUE TITLE
Grade Cientifica falha no mais-digitos

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#50]
Exemplo de caso que deveria fazer "+" , mas está com bug, https://osm.codes/BR+av

O click no "+" amarelo pode seguir do https://osm.codes/BR+6 para o `BR+67`, até o `BR+67777777777`, funciona.

Uma estratégia simples para o "+" avança em qualquer situação, é  o último dígito quando for "não-hierárquico", e só depois concatenar  o `7` (ao invés de apenas concatenar direto). Basta então substituir por nada a regex `[^0-9a-f]$`, antes de concatenar.

Nesse caso do `av`   o último dígito é `v`, portanto um dígito não-hierárquico, seria reduzido a `a` e então concatenado a `7`, portanto  https://osm.codes/BR+a7  que é uma célula menor que `av` (portanto comportamento esperado).

**Comment by 0e1** [comment]
Apliquei a sugestão conforme o commit referenciado acima.
