### ISSUE TITLE
Botão "Clear all" deveria se limitar ao que diz

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#51]
Seguindo uma lógica intuitiva de UI/UIX, o botão "Clear all" deveria se limitar a fazer apenas o que diz que é limpar seleções, e não _também_ a dar zoom mostrando o município inteiro.

Aconteceu o seguinte: escolhi um lugar ideal no mapa como amostra de captura de tela, porém já tinha clicado em vários pontos deixando várias seleções e só queria limpar a seleção deixando só uma e sem mudar o zoom. Então clico em "Clear all", o site limpa a seleção mas perco o local porque dá zoom out. Então tive que dar "Back" no histórico para recuperar, ENTER, reajustar o nível de seleção, clicar até achar, dar "Clear all", porque mostra seleção que não quero, dar BACK etc etc etc e de novo etc. E tive que refazer o roteiro várias vezes até acertar o ponto certo para mostrar uma tela de **uma área** com **uma seleção** no local de **uma casa** eu quero. No fim preferi memorizar o local e clicar no local certo, com o nível certo, de primeira.

Ver também: #52 e #53.

**Comment by 0e1** [comment]
Removi esse comportamento em todas as interfaces.
