### ISSUE TITLE
Adicione o checkbox "Keep previous clicks"

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#52]
Junto ao "No tooltip" e "Disable zoom-click", adicione "Keep previous clicks", desabilitado por default.

No site +codes, cada clique que você der, só aparece uma seleção por vez e não fica vários boxes/seleções na tela.

Caso eu queira visualizar os cliques anteriores, eu habilito o "Keep previous clicks".

**Comment by 0e1** [comment]
Adicionei o checkbox. Mas, com comportamento invertido em relação ao solicitado, conforme @ppKrauss .
