### ISSUE TITLE
Link ou botão de zoom no município

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#53]
Como consequência de #51, que propõe remover o zoom out/all do "Clear all", sugiro que adicione um link no texto do nome do município que aparece no topo (exemplo, link https://test.osm.codes/BR-SP-Campinas na palavra "Campinas" em "OSMcode: {código} ◀️▶️ of **Campinas**)

![image](https://user-images.githubusercontent.com/4673289/236905852-c70a7699-64f5-4054-beff-260121be2841.png)

Ou como alternativa, adicione um botão "View current jurisdiction", junto ao "Clear all".

**Comment by 0e1** [comment]
Link implementado.
