### ISSUE TITLE
Botão "Clear all" não resseta link e código

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#55]
Depois de clicar em "Clear all", o site limpa as células selecionadas, mas esquece de ressetar o endereço na barra de endereço do navegador e limpar o código OSMcode no topo.

### Passos para reprodução
* Abra um município, exemplo https://test.osm.codes/BR-SP-Jumirim;
* _Zoom in_ em algum lugar e dê uns cliques;
* Clique em "Clear all";
* O endereço na barra de endereço do navegador continua com o endereço da última célula selecionada e o topo continua exibindo o geocódigo da célula.

Screenshot:

![image](https://github.com/osm-codes/gridMap-draftPages/assets/4673289/c5c7199b-975b-405a-a81c-a1505e43cdd8)

### Comportamento esperado
* Após clicar em "Clear all", o endereço da barra volta para https://test.osm.codes/BR-SP-Jumirim e o código volta para a string "(CLICK THE MAP)".

**Comment by 0e1** [comment]
Implementado. Reabrir a issue se necessário.

**Comment by IgorEliezer** [comment]
Quase lá. Falta ressetar o código no topo após o Clear All.

![image](https://github.com/osm-codes/gridMap-draftPages/assets/4673289/067ca80d-166b-48e7-bce8-52a53ba3311e)

https://test.osm.codes/BR-SP-AguasSaoPedro~B

**Comment by 0e1** [comment]
Adicionei o reset no topo. Pode testar.
