### ISSUE TITLE
Inverter comportamento popup na Colombia

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#57]
Como Colombia optou por usar o DIVIPOLA como canônico, no lugar de mostrar "jurisdiction code", precisa mostrar **"jurisdiction label"** com codigo ISO... Ou mais uma linha, mostrando ambos.

PS: outro bug, usar utf8 na unidade, "Area: 32 **m²**" ao inves de "m2"

![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/96c00087-fa55-4f06-bcce-3b4cd1f41728)

https://test.osm.codes/CO-15001~7CS00

**Comment by 0e1** [comment]
Implementado. São exibidos os dois. Tanto em CO quanto em BR. Ver imagens abaixo.

![screen01](https://github.com/osm-codes/gridMap-draftPages/assets/41844788/fdfc6240-3178-484c-8b39-097af42c8333)
![screen](https://github.com/osm-codes/gridMap-draftPages/assets/41844788/1340bfd8-effc-4077-abb1-7ac54d79ce04)
