### ISSUE TITLE
Link para nova guia com página de ajuda

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#58]
Por exemplo "Level" em 
![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/106b8dcd-a995-4a27-a94d-2db41c68d346)

Teria um link para com `target="_help"`  para https://wiki.addressforall.org/doc/osmc:Viz/Navega%C3%A7%C3%A3o

**Comment by 0e1** [comment]
Adicionei o link em todas as interfaces. Exemplo: http://osm.codes/BR-SP-Campinas~PB.
