### ISSUE TITLE
Geo URI não está sendo resolvida pelo municipio

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#60]
Provavel bug de javascript (*undefined*), ver por exemplo este ponto sobre Tunja https://osm.codes/geo:5.533333,-73.366667

**Comment by 0e1** [comment]
Correção em https://github.com/osm-codes/GGeohash/commit/bedb39ea6fe3f7250b03c4b133c884a822ee525d.

**Comment by 0e1** [comment]
O problema ainda era um efeito colateral do shift feito na grade logística da Colombia.
Antes, usar 30 bits (quando não for informada a incerteza) retornava uma célula L15 (4m). Com o shitf é preciso 33 bits para retornar uma célula L16.5 (5.7m). O commit citado no comentário anterior corrige o valor default (quando a incerteza não for informada) para 33 bits.

Teste em : https://test.osm.codes/geo:5.533333,-73.366667.
