### ISSUE TITLE
Caractere estranho na string do link do código científico

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#61]
Coisa simples. Parece que era para ser um sinal ou emoji de mais (➕), mas está aparecendo um D dentro de um círculo (Ⓓ ou 🇩).

![image](https://github.com/osm-codes/gridMap-draftPages/assets/4673289/f51152b6-5f51-4a35-ba60-a374d92987a7)

Confirmado no Chrome e Mozilla.

**Comment by 0e1** [comment]
Foi solicitado que _in the Scientific grid: DFB5AA_ exibisse o código do país: _in the Scientific grid: BR+DFB5AA_. No html está correto.

Usamos a fonte https://pt.wikipedia.org/wiki/FE-Schrift, http://www.autokennzeichen.info/kennzeichen-schriftart.htm, http://web.archive.org/web/20230213064917/http://www.andyhoppe.com/design/fonts/euro-plate-font/. Ver https://github.com/osm-codes/gridMap-draftPages/issues/9.

É uma questão de fonte. Nela o símbolo `+` é um d dentro de um círculo de estrelas. Outro exemplo: `?` é um d dentro de uma elipse.

Então, não temos como usar **+** nessa fonte. Ou usar alguma alternativa.

**Comment by 0e1** [comment]
Resolvido em https://github.com/osm-codes/gridMap-draftPages/issues/83
