### ISSUE TITLE
Não fazemos propanda para terceiros

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#63]
Remover `attributionControl` do leaftlet, conforme https://gis.stackexchange.com/questions/192088/how-to-remove-attribution-in-leaflet

Regras gerais:

1. Sempre remover o *default*, não permitimos propaganda.
2. Juridicamente os créditos já foram dados a todos colaboradores, ao  expormos publicamente em *git* todos nossos códigos-fonte, não faz sentido dar **atribuição adicional** a uma biblioteca ou *dataset* especificos sem dar a todos. Por regra não fazemos atribuição adicional.
3. Se por acaso alguma atribuição adicional fizer sentido, criar uma versão reduzida de "info" para uma **página isolada discriminando os  créditos**.

**Comment by 0e1** [comment]
Foi removido de todas as interfaces.

Regras gerais adicionadas na wiki. Ver https://wiki.addressforall.org/w/index.php?title=osmc%3AViz%2FNavega%C3%A7%C3%A3o&type=revision&diff=1718&oldid=1354.
