### ISSUE TITLE
Na grade científica usar a expressão com ponto ou final maíuscula quando dígito não-hierárquico

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#65]
Conforme discutido no  [Draft-explain do exemplo de Tunja ](https://wiki.addressforall.org/doc/osmc:Conven%C3%A7%C3%B5es/Grade_cient%C3%ADfica_multifinalit%C3%A1ria/Draft-explain#Exemplo_de_Tunja), percebemos que o público fica confuso com a questão da hierarquia, quando ocorre digito-a-dígito e quando não.  Exemplos:

* [c3598aefc.Q](https://osm.codes/CO+c3598aefcQ) ⊂    [c3598aefc](https://osm.codes/CO+c3598aefc) ⊂  [c3598a](https://osm.codes/CO+c3598a) ⊂  [c3598.R](https://osm.codes/CO+c3598R) 
* [c359a0](https://osm.codes/CO+c359a0) ⊂ [c359a.H](https://osm.codes/CO+c359aH) ⊂  [c359a](https://osm.codes/CO+c359a) 

A rigor, para [expressar Natural Codes base **16h**](https://wiki.addressforall.org/doc/C%C3%B3digo_natural#/media/Arquivo:KraEtAll2019-fig11-ordBases.png) devemos usar a seguinte sintaxe:

* maiúsculo quando não for hexadecimal: dígitos finais `GQ HMRV JKNPSTZY`
* minúsculo quando for hexadecimal: `0123456789 abcdef` 

Em caso de fonte que não possua minúsculas, usar cor ou ponto para destacar o dígito final não-hierárquico.

**Comment by 0e1** [comment]
Outro commit realizado https://github.com/osm-codes/gridMap-draftPages/commit/0e1a937c0c5f394dbdaf7731d413c79f3181a648.


Implementado o que foi solicitado. Testar nas versões teste e produção.
