### ISSUE TITLE
Checkbox "Disable zoom-click" poderia não dar pan

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#66]
Da mesma forma, quando preciso fazer vários testes numa área específica do mapa, eu não quero perdê-la ou nem que a tela fique se deslocando.

Sugiro que o checkbox "Disable zoom-click" não só desabilite o _zoom-in_ ao clicar, mas também que a tela não desloque para se centralizar na célula selecionada.

**Comment by 0e1** [comment]
Implementei o que solicitou. Se tiver problemas reabra a issue.

**Comment by IgorEliezer** [comment]
Perfeito! Obrigado.
