### ISSUE TITLE
Transição para AFAcodes

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#67]
Por questões de direitos sobre marca, estamos migrando de OSMcodes para AFAcodes.
Já está ok o domínio no nosso servidor, http://afa.codes aponta para lá. 

1. Configurar HTTPS
2. Copiar e colar integralmente o NGINX do OSM.codes (git, api e test) para AFA, sobretudo o aplicativo /geocódigo. <br/>NOTA: Cuidado que o do `sites_available/osm.codes` está mais atualizado do que o git de [config.nginx](https://github.com/osm-codes/WS/blob/main/src/config.nginx).
3. Testar e muito cuidado para não comprometer OSMcodes existente, ele vai continuar operando.
4.  ... postar comments com o que mais precisar.

PS: se preferir copiar/colar como 2 arquivos, lembrar que texto NGINX de `osm.codes` é bem maior (tem lixos) do que `afa.codes`... Problema depois decidir no git se quebra o  `src/config.nginx` em dois.

-----

![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/22bd51a1-ceca-40eb-acd7-cefff78b0858)

**Comment by ppKrauss** [comment]
@0e1 auxiliar Carlos no que for preciso, se forem dividir tarefas ficar com a parte do endpoints da API.

**Comment by crebollobr** [comment]
Feita a configuração e certificado ssl

**Comment by 0e1** [comment]
> 2\. NOTA: Cuidado que o do `sites_available/osm.codes` está mais atualizado do que o git de [config.nginx](https://github.com/osm-codes/WS/blob/main/src/config.nginx).

Compatibilizei os dois no commit https://github.com/osm-codes/WS/commit/f59b967c8cbb95c8ec509c052fb978ba1eef058d.




> PS: se preferir copiar/colar como 2 arquivos, lembrar que texto NGINX de `osm.codes` é bem maior (tem lixos) do que `afa.codes`... Problema depois decidir no git se quebra o `src/config.nginx` em dois.


Minha sugestão é manter 1 só. E fazer assim:
- config.nginx -> sites_available/osm.codes
- config.nginx -> `sed 's/osm.codes/afa.codes/g' config.nginx > sites_available/afa.codes`

**Comment by 0e1** [comment]
Atualizando a situação.

Está sendo mantido **apenas um arquivo**. Ver a configuração em [WS/config.nginx](https://github.com/osm-codes/WS/blob/main/src/config.nginx).

Acrescentando `(.+\.)?afa.codes` no `server_name` não é preciso manter dois arquivos de configurações diferentes com o mesmo conteúdo.

Exemplo da configuração atual:

```sh
server {
    server_name git-site.osm.codes git-site.afa.codes;

    listen              80;
    listen              443 ssl;
    include /etc/nginx/ssl.conf;

    location ~ ^/?.+ {
            rewrite
                ^/?(.*)$
                /$1
                break;
            proxy_pass http://osm-codes.github.io;
    }
}
```
