### ISSUE TITLE
Incluir abreviações UF-UF para as capitais do Brasil e RegistroBR para válidas 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#69]
## Capitais
Por exemplo https://osm.codes/BR-SP-SaoPaulo~MCGBM7 pode ser expresso como https://osm.codes/BR-SP-SPA~MCGBM7 mas, por ser capital poderia ainda usar https://osm.codes/BR-SP-SP~MCGBM7 . A sintaxe usual de capital é UF-UF.

## DF
O Distrito Federal deveria ser acessível por `BR-DF`, por exemplo https://osm.codes/BR-DF~6W1MM

## RegistroBR
Os domínios municipais do Brasil [resgistrados](https://registro.br/dominio/categorias/) com mais de duas letras podem se tornar redirecionadores:

![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/a9684a3a-cb7a-492d-b2be-f45540353704)

Seriam válidos por exemplo https://osm.codes/BR-Sampa~MCGBM7 e https://osm.codes/BR-SP-Sampa~MCGBM7

**Comment by 0e1** [comment]
Sobre registroBR:

- Sem ambiguidade quando usados os três níveis;
- Algumas ambiguidades quando usado BR-dominio;
- _9guacu_ exigiu mudanças no nginx;
- 54 cidades com dominio

Links para testar

https://test.afa.codes/BR-PA-Anani
https://test.afa.codes/BR-SP-Aparecida
https://test.afa.codes/BR-SE-Aju
https://test.afa.codes/BR-SP-Barueri
https://test.afa.codes/BR-PA-Belem
https://test.afa.codes/BR-MG-Bhz
https://test.afa.codes/BR-RR-Boavista
https://test.afa.codes/BR-DF-Bsb
https://test.afa.codes/BR-PB-Campinagrande
https://test.afa.codes/BR-SP-Campinas
https://test.afa.codes/BR-MS-Morena
https://test.afa.codes/BR-RS-Caxias
https://test.afa.codes/BR-MG-Contagem
https://test.afa.codes/BR-MT-Cuiaba
https://test.afa.codes/BR-PR-Curitiba
https://test.afa.codes/BR-BA-Feira
https://test.afa.codes/BR-SC-Floripa
https://test.afa.codes/BR-CE-Fortal
https://test.afa.codes/BR-PR-Foz
https://test.afa.codes/BR-GO-Goiania
https://test.afa.codes/BR-SP-Gru
https://test.afa.codes/BR-PE-Jab
https://test.afa.codes/BR-PB-Jampa
https://test.afa.codes/BR-SC-Joinville
https://test.afa.codes/BR-MG-Jdf
https://test.afa.codes/BR-PR-Londrina
https://test.afa.codes/BR-AP-Macapa
https://test.afa.codes/BR-AL-Maceio
https://test.afa.codes/BR-AM-Manaus
https://test.afa.codes/BR-PR-Maringa
https://test.afa.codes/BR-RN-Natal
https://test.afa.codes/BR-RJ-Niteroi
https://test.afa.codes/BR-RJ-9guacu
https://test.afa.codes/BR-SP-Osasco
https://test.afa.codes/BR-TO-Palmas
https://test.afa.codes/BR-RS-Poa
https://test.afa.codes/BR-RO-Pvh
https://test.afa.codes/BR-PE-Recife
https://test.afa.codes/BR-SP-Ribeirao
https://test.afa.codes/BR-AC-Riobranco
https://test.afa.codes/BR-RJ-Rio
https://test.afa.codes/BR-BA-Salvador
https://test.afa.codes/BR-RS-Santamaria
https://test.afa.codes/BR-SP-Santoandre
https://test.afa.codes/BR-SP-Saobernardo
https://test.afa.codes/BR-RJ-Saogonca
https://test.afa.codes/BR-SP-Riopreto
https://test.afa.codes/BR-SP-Sjc
https://test.afa.codes/BR-MA-Slz
https://test.afa.codes/BR-SP-Sampa
https://test.afa.codes/BR-SP-Sorocaba
https://test.afa.codes/BR-PI-The
https://test.afa.codes/BR-MG-Udi
https://test.afa.codes/BR-ES-Vix

https://test.afa.codes/BR-Anani
https://test.afa.codes/BR-Aju
https://test.afa.codes/BR-Barueri
https://test.afa.codes/BR-Bhz
https://test.afa.codes/BR-Bsb
https://test.afa.codes/BR-Campinagrande
https://test.afa.codes/BR-Campinas
https://test.afa.codes/BR-Morena
https://test.afa.codes/BR-Contagem
https://test.afa.codes/BR-Cuiaba
https://test.afa.codes/BR-Curitiba
https://test.afa.codes/BR-Feira
https://test.afa.codes/BR-Floripa
https://test.afa.codes/BR-Fortal
https://test.afa.codes/BR-Foz
https://test.afa.codes/BR-Gru
https://test.afa.codes/BR-Jab
https://test.afa.codes/BR-Jampa
https://test.afa.codes/BR-Joinville
https://test.afa.codes/BR-Jdf
https://test.afa.codes/BR-Londrina
https://test.afa.codes/BR-Macapa
https://test.afa.codes/BR-Maceio
https://test.afa.codes/BR-Manaus
https://test.afa.codes/BR-Maringa
https://test.afa.codes/BR-Natal
https://test.afa.codes/BR-Niteroi
https://test.afa.codes/BR-9guacu
https://test.afa.codes/BR-Osasco
https://test.afa.codes/BR-Palmas
https://test.afa.codes/BR-Pvh
https://test.afa.codes/BR-Recife
https://test.afa.codes/BR-Rio
https://test.afa.codes/BR-Salvador
https://test.afa.codes/BR-Santamaria
https://test.afa.codes/BR-Saogonca
https://test.afa.codes/BR-Sjc
https://test.afa.codes/BR-Slz
https://test.afa.codes/BR-Sampa
https://test.afa.codes/BR-Sorocaba
https://test.afa.codes/BR-The
https://test.afa.codes/BR-Udi
https://test.afa.codes/BR-Vix

**Comment by 0e1** [comment]
> ## DF
> 
> O Distrito Federal deveria ser acessível por `BR-DF`, por exemplo https://osm.codes/BR-DF~6W1MM

Testar.

Exemplos:

https://test.osm.codes/BR-DF~6W1MM
https://test.afa.codes/BR-DF~6W1MM
https://test.osm.codes/CO-DC~5ST5ZQD
https://test.afa.codes/CO-DC~5ST5ZQD




> ## Capitais
> 
> Por exemplo https://osm.codes/BR-SP-SaoPaulo~MCGBM7 pode ser expresso como https://osm.codes/BR-SP-SPA~MCGBM7 mas, por ser capital poderia ainda usar https://osm.codes/BR-SP-SP~MCGBM7 . A sintaxe usual de capital é UF-UF.

Testar.

Exemplo: 

https://test.osm.codes/BR-SP-SP~MCGBM7
https://test.afa.codes/BR-SP-SP~MCGBM7

**Comment by 0e1** [comment]
Bug detectado após as alterações: 

- https://test.osm.codes/BR-SP
- https://test.osm.codes/CO-BOY

Deixaram de direcionar para a página do país.

Assim, usar dominios com _duas ou mais letras_ conflita com códigos ISO de estados.

**Comment by 0e1** [comment]
Definições escritas na wiki (rascunho): https://wiki.addressforall.org/doc/osmc:Api.
