### ISSUE TITLE
quando solicitado tooltip não aparece em todos

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#7]
Exemplo testado em https://osm.codes/BR-SP-Campinas~3SUH

![image](https://user-images.githubusercontent.com/1651447/198888248-1a0669f5-5456-48f5-95ac-068185320cf9.png)

**Comment by ppKrauss** [comment]
Ver também #18

**Comment by 0e1** [comment]
Consolidada em https://github.com/osm-codes/gridMap-draftPages/issues/56#issuecomment-1548419263.
