### ISSUE TITLE
Falha Firefox no click, aparece apenas ponto

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#72]
Usando Firefox:

1. Entrar em https://afa.codes/BR-DF-Brasilia
2. Clicar dentro da cidade

Variação: selecionar nível, por exemplo L7.5, mesmo bug:
![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/2c2afa7d-4070-4521-8926-ae0e93f47d9c)

Aparece apenas ponto

**Comment by IgorEliezer** [comment]
Para mim não apareceu o bug
![image](https://github.com/osm-codes/gridMap-draftPages/assets/4673289/0ac6daba-6030-4ee5-b714-eb20e791700f)

**Comment by 0e1** [comment]
Eu **não** consegui reproduzir o bug nas interfaces em _produção_ ou _test_.

O ponto é obtido da geometria da célula no lado do cliente, pelo javascript. Então a api retornou a geometria.

Um caminho de investigação é usar F12 e verificar se a requisição da geometria foi de fato respondida e se no console aparece algum erro relacionado ao javascript.

**Comment by 0e1** [comment]
Vou fechar a issue já que não conseguimos reproduzir o bug.
