### ISSUE TITLE
Código da cobertura inconsistente com valor mostrado

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#73]
O código da célula de cobertura possui apenas um dígito, mas ao clicarmos na cobertura aparece um código absoluto, que não faz mais sentido exceto para bug: 

1. Criar propriedade GeoJSON de retorno chamada `debug`: nela incluir o que for necessário como o "código b32 fake" que é de interesse apenas do desenvolvedor. Incluir também o código científico equivalente.

3. Mostrar o código correto nos polígonos da cobertura.

![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/dcf9f2fe-8144-4c21-bb4d-4fc6f631a185)

**Comment by 0e1** [comment]
No caso de células de cobertura é retornado atualmente:

![screen](https://github.com/osm-codes/gridMap-draftPages/assets/41844788/94e83996-9305-47a3-8da2-16ffb824bff6)

No commit https://github.com/osm-codes/gridMap-draftPages/commit/47b2cef04f5068a2ae0d54d6ffa363bfa5903fa0 passei a exibir no _tooltip_ o _index_ da célula. Não é necessário criar outra propriedade no geojson. O código scientifico é retornado em `code`, `index` retorna o índice da célula (letra do alfabeto b32nvu) e `base` retorna a base utilizada em `code`.

O pequeno ajuste descrito no commit mencionado  acima resulta em:

![screen01](https://github.com/osm-codes/gridMap-draftPages/assets/41844788/53a7d650-ed5c-4751-bb15-adac6ea055e5)

Mudanças disponíveis para teste em http://test.afa.codes.

**Comment by 0e1** [comment]
Mudanças implantadas na produção.
