### ISSUE TITLE
Colocar atribuição OpenStreetMap

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#74]
Isso pode trazer problemas de relacionamento com a comunidade e fundação OSM.

Por força da licença ODBL, temos que colocar a atribuição `© Contribuidores OpenStreetMap` (com link para https://www.openstreetmap.org/copyright) em algum lugar visível, talvez no rodapé ou logo abaixo do frame do mapa.

![image](https://github.com/osm-codes/gridMap-draftPages/assets/4673289/7016e242-22c2-4312-875c-fc9d6156747c)

**Comment by ppKrauss** [comment]
@0e1 , precisamos de um mero "info" co link para a pagina de maiores informações, onde se expressam as licenças e créditos. 
O Leaflet tem uma string longa mas precisamos de string curta.

**Comment by 0e1** [comment]
@IgorEliezer 
A atribuição existia e foi removida intencionalmente conforme https://github.com/osm-codes/gridMap-draftPages/issues/63. Eram dados créditos a _Leaflet_, _OSM_, _Mapbox_ ou _CARTO_.

@ppKrauss 

Lembrar que a atribuição foi removida conforme https://github.com/osm-codes/gridMap-draftPages/issues/63.

***
Adicionei novamente a atribuição ao mapa, na versão _teste_. Apenas com um link _info_ apontando para a página da wiki https://wiki.addressforall.org/doc/osmc:Atribuições. Exemplo: http://test.afa.codes/BR-SP-SaoPaulo

![screen](https://github.com/osm-codes/gridMap-draftPages/assets/41844788/54175cf5-8199-46ed-bf5a-4d5438fcc7e3)

**Comment by ppKrauss** [comment]
O simples "info" é o que precisávamos, resolvido!  @IgorEliezer rechear a pagina Wiki, já foi criada. Fechando a isso...

**Comment by 0e1** [comment]
Adicionei a atribuição as demais interfaces (test e produção).

**Comment by IgorEliezer** [comment]
Vê se está suficiente: https://wiki.addressforall.org/doc/osmc:Atribui%C3%A7%C3%B5es.

Fechando já que a feature foi implementada.
