### ISSUE TITLE
formatar geocodigo na visualização principal 

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#8]
Formatar com pontos, a cada 3 da esquerda para a direita: marcando a hierarquia. Por exemplo `AB233CC` como `AB2.33C.C`.

Implementações SQL e Javascript:

```sql
select regexp_replace('AB233CC', '(...)(?!$)', '\1.', 'g');
```

```js
const reg = /(...)(?!$)/g
console.log( "AB233CC".replace(reg, '$1.') )
```

**Comment by 0e1** [comment]
![índice](https://user-images.githubusercontent.com/41844788/199321499-27fb6017-3676-49e0-b475-620c12724218.jpeg)
