### ISSUE TITLE
Codificação do CEP é definitiva, vale o hifem

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#82]
Por exemplo https://test.afa.codes/BR-49750~CMH funciona, mas https://test.afa.codes/BR-49750-CMH  também deveria funcionar.

Regex: `BR\-\d{5,5}\-.*`.  Aparentemente não há conflito com as demais regexes, resta conferir. Ver também isso que sugere simplificar todas elas, já que a responsabilidade de resolver é do PostgreSQL, o NGINX só precisa distingir prefixos e casos gerais.

**Comment by 0e1** [comment]
Vou consolidar essas definições dispersas em issues na página (rascunho): https://wiki.addressforall.org/doc/osmc:Api


O problema não está na api:

- https://test.afa.codes/geo:osmcodes:BR-49750-CMH.json
- https://test.afa.codes/geo:osmcodes:BR-49750~CMH.json

funcionam.


Problema era em main.js. Corrigi em https://github.com/osm-codes/gridMap-draftPages/commit/531a7d83afc9a2d463b4886fc83a482a0363ac8f.
