### ISSUE TITLE
No Brasil e na colombia indicar na tarja amarela o nome curto

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#84]
No caso do Brasil por exemplo, ao invés de "BR-SP-Sao.Paulo\~FC3NY", "BR-SP-SPA\~FC3NY"
![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/1e147d1a-e674-40ac-830e-fad9923e83e5)
é simples?  Requer marcar uma das abreviações  como "preferida" e usar ela. No caso da Colômbia já é oficial. o DIVIPOLA.

**Comment by 0e1** [comment]
Implementado.
