### ISSUE TITLE
Bug introduzido, revisar modificações recentes

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#85]
por exemplo https://afa.codes/CO-15001~HQCT  parou de funcionar, bug na chamada do server:

![image](https://github.com/osm-codes/gridMap-draftPages/assets/1651447/e0d1ee3e-dde6-4f6b-9395-86ae5f7caa49)

Idem Brasil, por ex. https://afa.codes/BR-SP-SaoJoseCampos~2YNHP

----

Mas navegando a partir do município vai (!), https://afa.codes/CO-15001  depois click no mapa.

Conclusão, Server, client ou NGINX?  tá mais com cara de client.

**Comment by 0e1** [comment]
Situação já resolvida. Como essa issue é antiga, códigos citados nela podem não funcionar após iniciar as coberturas em zero.
