### ISSUE TITLE
Texto de tooltips das setas de níveis  

### ISSUE THREAD

**Issue by IgorEliezer** [osm-codes/gridMap-draftPages#87]
(Baixa prioridade)
Quando se sobrevoa o ponteiro do mouse sobre as setas < e >, vemos estes dois tooltips:
* less digits (previous larger level)
* more digits (next smaller level)

Sugiro trocar para:
* higher level (less digits)
* lower level (more digits)

Motivo é que "previous" e "next" querem dizer algo que ocorreu antes ou depois no histórico, como há em editores de imagem e CAD "Go to the previous/next view" ou "Zoom previous/next" para voltar ou avançar para o view anterior/posterior salvo no histórico. 

No caso do afa.codes, previous larger level simplesmente muda o view para um zoom mais alto, mesmo que nunca foi salvo no histórico do navegador. E "larger/smaller level" soa muito estranho; level se refere a altura, e não a tamanho; smaller/larger não se aplicariam aqui. O que se tem é afastando zoom e aproximando zoom, então "lower level/higher level" é melhor, mais intuitivo e curto.

**Comment by 0e1** [comment]
Implementado. Disponível para teste em https://test.afa.codes.

**Comment by IgorEliezer** [comment]
Funcionou. Obrigado.
