### ISSUE TITLE
Camarões: A cidade de Saa aparece assim: SaA

### ISSUE THREAD

**Issue by ThierryAJean** [osm-codes/gridMap-draftPages#88]
![image](https://github.com/user-attachments/assets/5510109c-3268-473e-8b48-895d171ea30a)

**Comment by 0e1** [comment]
Problema foi ocasionado pela aspa simples no nome da cidade quando da geração do _isolabel_ext_.

Três casos foram encontrados e corrigidos em Camarões. Foram esses:


https://afa.codes/CM-SU-Maan
https://afa.codes/CM-AD-Nganha
https://afa.codes/CM-CE-Saa
