### ISSUE TITLE
Falha na ordenação das coberturas

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/gridMap-draftPages#91]
quando usamos "order by codigo_b16h" precisamos lembrar que a ordenação de string nao vale. Se o último caracter for não-hierárquico ocorre quebra a ordem-string. Como [recomendado na Wiki](https://wiki.addressforall.org/doc/C%C3%B3digo_Natural#Ordena%C3%A7%C3%B5es_lexicogr%C3%A1fica_e_num%C3%A9rica) no tipo b16h pode ser ordenado com translate: 
```sql
ORDER BY translate(
    b16h,
   'GHJ01K23MN45R67QRS89TabVZcdYef',
    '0123456789ABCDEFGHIJKLMNOPQRST'
 ) -- ou apenas a tradução do último dígito`
```
ou, se estiver disponivel o ID  binário (_varbit_ ou _hBig_) é mais direto, dispensa gambiarra. 

PS: cuidado que bitstrings de tamanho variável (ex. cobertura-base misturada a cobertura-overlay) não podem ser ordenadas por _hiddenBig_ , só por _hBih_. 

Maiores detalhes em https://github.com/osm-codes/topSecret/issues/2#issuecomment-2274469454  (reproduzido abaixo)

-----

## Conclusão: o bug é do site

Partindo do exemplo de https://afa.codes/BR-SP-SaoBentoSapucai

![image](https://github.com/user-attachments/assets/b4b17aab-80fb-4f95-899b-9427a7b3c7ed)

Nós ordenamos por gid, o site deve ter usado a string b16h: vem primeiro o Z depois o Y.

Ver https://wiki.addressforall.org/doc/C%C3%B3digo_Natural#Ordena%C3%A7%C3%B5es_lexicogr%C3%A1fica_e_num%C3%A9rica  e a imagem abaixo:

![image](https://github.com/user-attachments/assets/1fb9a9dc-c9c0-4a46-b85a-186145d47347)

![image](https://github.com/user-attachments/assets/1fe73427-8b4b-4028-a2ac-583a2476ece4)

**Comment by 0e1** [comment]
Ordenação corrigida, conforme commit referenciado acima.

Em resumo:

```sql
ORDER BY
is_overlay ASC, -- células base ANTES de todas as células overlay.
hbig ASC
```

Ver teste em https://test.afa.codes/BR-SP-SaoBentoSapucai.

**Comment by 0e1** [comment]
Nova ordenação aplicada em todas as jurisdições em https://afa.codes e https://test.afa.codes.

**Comment by ppKrauss** [comment]
testado e resolvido
